### ISSUE TITLE
Pipfile.lock

### ISSUE THREAD

**Issue by FrederikPlahl** [AndreasZachariae/semantic_hierarchical_graph#2]
You've ignored the ```Pipfile.lock``` in your ```.gitignore``` in https://github.com/AndreasZachariae/semantic_hierarchical_graph/blob/2b185df8bfd73e7337eb46fda54e5bb9dceb4c9d/.gitignore#L98 but tried to copy it in your ```Dockerfile``` leading to an error while building.
Please include your ```Pipfile.lock``` in version control.

**Comment by AndreasZachariae** [comment]
Added current Pipfile.lock
